sudo: required
language: node_js
node_js:
  - "9"

services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker run docker-react npm run test -- --coverage
  - docker tag docker-react registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master
